cfg: models/yolov5x.yaml
data: ../defect_yolov5l/data.yaml
hyp: ''
epochs: 500
batch_size: 8
img_size:
- 992
- 992
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
weights: ''
name: ''
device: ''
multi_scale: false
single_cls: false
